#!/bin/bash

# args: message, default
# puts the result into $ANSWER
ask_string()
{
	echo -n "$1 [$2]: "
	read -r ANSWER

	if [ -z "$ANSWER" ]
	then
		ANSWER="$2"
	fi
}


# CONFIG


if [ "$INTERACTIVE" = false ]
then
	PREFIX="${PREFIX:-/usr}"
	USE_BIN=${USE_BIN:-true}
	DATA_DIR='~/.acdc' # passed verbatim during substitution
else
	INTERACTIVE=true

	if [ -z "$PREFIX" ]
	then
		ask_string "Choose an installation prefix" /usr
		PREFIX="$ANSWER"
	fi

	if [ -z "$DATA_DIR" ]
	then
		ask_string 'Choose a directory for storing data' '~/.acdc'
		DATA_DIR="$ANSWER"
	fi

	echo -n "Do you want to add an \"acdc\" command? [Y/n] "
	read -r ANSWER
	if [[ "$ANSWER" =~ ^([Yy]([Ee][Ss])?)?$ ]]
	then
		USE_BIN=true
	else
		USE_BIN=false
	fi

	echo
fi

REL_INSTALL_DIR="$PREFIX/share/acdc-toolkit"
INSTALL_DIR="$ROOT$REL_INSTALL_DIR"


# CHECKS


if [ -e "$INSTALL_DIR" ]
then
	echo 'The installation directory already exists.' >&2
	echo 'Please uninstall the previous version first.' >&2
	exit 1
fi


# INSTALLATION


mkdir -p "$INSTALL_DIR"
cp -r ./. "$INSTALL_DIR"

find "$INSTALL_DIR" -type f -exec sed -i \
	 "s|@_INSTALL_DIR_@|$REL_INSTALL_DIR|g
	  s|@_DATA_DIR_@|$DATA_DIR|g" {} \;
rm -rf "$INSTALL_DIR/packaging" "$INSTALL_DIR"/.git*

if $USE_BIN
then
	mkdir -p "$ROOT$PREFIX/bin/"
	install -m 755 "$INSTALL_DIR/acdc" "$ROOT$PREFIX/bin/"

	if $INTERACTIVE && ! grep -q "$ROOT$PREFIX/bin" <<<"$PATH"
	then
		echo "The command has been installed in $ROOT$PREFIX/bin"
		echo 'Please consider adding this to your $PATH.'
	fi
fi

rm "$INSTALL_DIR/acdc"
