#!/bin/bash


# args: message, default
# puts the result into $ANSWER
ask_string()
{
	echo -n "$1 [$2]: "
	read -r ANSWER

	if [ -z "$ANSWER" ]
	then
		ANSWER="$2"
	fi
}


PATH="$PWD/tools:$PATH"


# Config

if [ "$INTERACTIVE" = false ]
then
	PREFIX="${PREFIX:-/usr}"
	USE_BIN=${USE_BIN:-true}
	DEFAULT_LOCAL_PREFIX="${DEFAULT_LOCAL_PREFIX:-~/.local}"
	DEFAULT_DATA_DIR="${DEFAULT_DATA_DIR:-~/.acdc}"
else
	INTERACTIVE=true

	if [ -z "$PREFIX" ]
	then
		ask_string "Choose an installation prefix" '/usr'
		PREFIX="$(eval echo "$ANSWER")"

		mkdir -p "$PREFIX"
	fi

	if [ -z "$DEFAULT_LOCAL_PREFIX" ]
	then
		if [ -w "$PREFIX" ]
		then
			DEFAULT_LOCAL_PREFIX="$PREFIX"
		else
			ask_string "Choose an user-writeable installation prefix" '~/.local'
			DEFAULT_LOCAL_PREFIX="$(eval echo "$ANSWER")"
		fi
	fi

	if [ -z "$DEFAULT_DATA_DIR" ]
	then
		ask_string 'Choose a directory for storing data' '~/.acdc'
		DEFAULT_DATA_DIR="$(eval echo "$ANSWER")"
	fi

	if [ -z "$USE_BIN" ]
	then
		echo -n "Do you want to add an \"acdc\" command? [Y/n] "
		read -r ANSWER
		if [[ "$ANSWER" =~ ^([Yy]([Ee][Ss])?)?$ ]]
		then
			USE_BIN=true
		else
			USE_BIN=false
		fi
	fi

	echo
fi

GIT_UPSTREAM_URL="$(git config --get remote.origin.url 2> /dev/null)"


# Other constants

INSTALL_DIR="$ROOT$PREFIX/share/acdc-toolkit"


# Checks

if [ -e "$INSTALL_DIR" ]
then
	echo 'The installation directory already exists.' >&2
	echo 'Please uninstall the previous version first.' >&2
	exit 1
fi


set -e


# Preparing files

BUILD_DIR="$(mktempdir)"

cp -r ./. "$BUILD_DIR"

maybe_sudo rm -rf "$INSTALL_DIR/packaging" "$INSTALL_DIR"/.git*

find "$BUILD_DIR" -type f -exec tools/substitute.sh {} \
	 'PREFIX' "$PREFIX" \
	 'USE_BIN' "$USE_BIN" \
	 'GIT_UPSTREAM_URL' "$GIT_UPSTREAM_URL" \
	 'DEFAULT_LOCAL_PREFIX' "$DEFAULT_LOCAL_PREFIX" \
	 'DEFAULT_DATA_DIR' "$DEFAULT_DATA_DIR" \;


# Installation

maybe_sudo mkdir -p "$INSTALL_DIR"
maybe_sudo cp -r "$BUILD_DIR/." "$INSTALL_DIR"

if $USE_BIN
then
	maybe_sudo mkdir -p "$ROOT$PREFIX/bin/"
	maybe_sudo mv "$INSTALL_DIR/acdc" "$ROOT$PREFIX/bin/"

	if $INTERACTIVE && ! grep -q "$ROOT$PREFIX/bin" <<<"$PATH"
	then
		echo "The command has been installed in $ROOT$PREFIX/bin"
		echo 'Please consider adding this to your $PATH.'
	fi
fi


# Cleanup

rm -rf "$BUILD_DIR"
