#!/bin/sh

TOOLKIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

pipenv run "$TOOLKIT_DIR"/toolkit.py "$@"
if [ "$?" -eq 1 ]; then
    pipenv install
    pipenv run "$TOOLKIT_DIR"/toolkit.py "$@"
fi