#!/bin/bash

# Usage: confirm MSG
# Returns 0 on positive or empty answer, 1 otherwise.


while true
do
	echo -n "$1 [Y/n]? "

	read ANSWER

	if [[ "$ANSWER" =~ ^([Yy][eEsS]*)?$ ]]
	then
		exit 0
	elif [[ "$ANSWER" =~ ^[Nn][oO]*? ]]
	then
		exit 1
	fi
done
