#!/bin/sh

# Usage: confirm MSG
# Returns 0 on positive or empty answer, 1 otherwise.


while true
do
    printf '%s [Y/n]? ' "$1"

    read ANSWER

    if expr "$ANSWER" : '^\([Yy][EeSs]*\)\?$' > /dev/null
    then
        exit 0
    elif expr "$ANSWER" : '^\([Nn][OoNn]*\)\?$' > /dev/null
    then
        exit 1
    fi
done
