#!/bin/sh


export PREFIX='@_PREFIX_@'
INSTALL_DIR="$PREFIX/share/acdc-toolkit"


rm -f "$DATA_DIR/.installed"


# User components

pipenv --rm

if confirm 'Remove local data'
then
    rm -rf "$DATA_DIR/"
fi

if [ "$(command -v pyenv > /dev/null)" = "$PYENV_ROOT/bin/pyenv" ] && confirm 'Uninstall pyenv'
then
    rm -rf "$PYENV_ROOT/"
fi

if [ "$(command -v pipenv > /dev/null)" = "$LOCAL_PREFIX/bin/pipenv" ] && confirm 'Uninstall pipenv'
then
    pip3 uninstall pipenv
fi


# Trying to detect weither root privileges are required

sudo=''
if ! mkdir "$PREFIX" 2> /dev/null && ! touch "$PREFIX" 2> /dev/null
then
    sudo='sudo'
fi


# Global components

cd /
$sudo rm -f "$PREFIX/bin/acdc"
$sudo rm -rf "$INSTALL_DIR"
